### ISSUE TITLE
Add autogenerate apk feature

### ISSUE THREAD

**Issue by idealadarsh** [idealadarsh/Moment-of-Inertia#1]
Hello, I am trying to find a way to autobuild apk in apk branch of this repository on each pull request using Travis CI.

**Comment by gtsaousidis** [comment]
Hi, i made a pull request which made part of what you asked about the auto build and generate the apk on the apk branch. To completely done this task you need private information from the project which only the admin has. Here is a helpful link: [https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4](https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4)
